---
language: ruby
rvm:
- 1.9.3
- rbx-19mode
env:
  global:
  - PATH=/tmp/bin:$PATH
  - secure: ! 'C7ykJsEXx+w/rbgjd7HlGLPZm8JzIIMky1UMrIRprnW/y4whV/bmgdXNgdoZnILIJImHhLcLnnVoKSD9rk7aNeGUO7Psy4DubRGFea6RH373R6fes4sfb1zkXSWJZx9nqBBoeEG/kUlfzP5yiokFwqsGFIS4CQWu+SEezcDATt0='
  matrix:
  - DRIVER=chrome
  - DRIVER=selenium
before_install:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- sudo apt-get install imagemagick
- sudo sh -c 'cat script/hosts > /etc/hosts'
before_script:
- ./script/setup_browserid.rb
- ./script/install-chrome-driver.sh
