language: ruby
rvm:
  - 1.9.3
  - jruby
  - rbx-19mode
env:
  global:
    - PATH=/tmp/bin:$PATH
  matrix:
    - DRIVER=chrome
    - DRIVER=selenium
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - "sudo sh -c 'cat script/travis/hosts > /etc/hosts'"
before_script:
  - "./script/travis/setup-browserid.sh"
  - "bundle exec rake servers:browserid:start > /tmp/browserid.log 2>&1 &"
  - "./script/install-chrome-driver.sh"
